FROM python:3.7

RUN pip install fastapi
RUN pip install uvicorn
RUN pip install motor pymongo[srv]
RUN pip install pandas
RUN pip install python-multipart
RUN pip install python-jose[cryptography]
RUN pip install passlib[bcrypt] 
RUN pip install pyppeteer
RUN pip install pytz
RUN pip install aiofiles
RUN pip install jinja2

RUN apt update
RUN apt full-upgrade -y
RUN apt-get install -y chromium-common libasound2 libatk-bridge2.0-0 libatk1.0-0 libatomic1 libatspi2.0-0 libavcodec58 libavformat58 libavutil56 libc6 libcairo2 libcups2 libdbus-1-3 libdrm2 libevent-2.1-6 libexpat1 libflac8 libfontconfig1 libfreetype6 libgbm1 libgcc1 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libharfbuzz0b libicu63 libjpeg62-turbo libjsoncpp1 liblcms2-2 libminizip1 libnspr4 libnss3 libopenjp2-7 libopus0 libpango-1.0-0 libpangocairo-1.0-0 libpng16-16 libpulse0 libre2-5 libsnappy1v5 libstdc++6 libvpx5 libwebp6 libwebpdemux2 libwebpmux3 libx11-6 libx11-xcb1 libxcb-dri3-0 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxml2 libxrandr2 libxrender1 libxslt1.1 libxss1 libxtst6 zlib1g
RUN wget http://ftp.ch.debian.org/debian/pool/main/c/chromium/chromium_83.0.4103.116-1~deb10u3_arm64.deb
RUN dpkg -i chromium_83.0.4103.116-1~deb10u3_arm64.deb
RUN apt-get -fy install

EXPOSE 80

COPY ./app /app
WORKDIR /app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]